spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_school_base_server?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8092
reaktor:
  publicKeyFile: "C:/claves/public_key.pem"
  urlCors: "http://localhost:8888, http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173"
  firebase_server_url: http://localhost:8083/
  http_connection_timeout: 30000